# Usa un'immagine base di Gradle compatibile con ARM/v8
FROM --platform=linux/arm64/v8 gradle:8.6.0-jdk17 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle assemble
RUN gradle fatJar

# Usa un'immagine base OpenJDK compatibile con ARM/v8
FROM --platform=linux/arm64/v8 openjdk:19

RUN mkdir /app
RUN mkdir /app/log

COPY --from=build /home/gradle/src/app/build/libs/ /app/
COPY --from=build /home/gradle/src/app/log /app/log

EXPOSE 3003
ENTRYPOINT ["java","-jar","/app/Middleware.jar"]